In [3]:
import numpy as np



In [4]:
import pandas as pd

In [5]:
arr1 = np.array([1, 2, 3])


In [6]:
arr2 = np.array([2, 4, 6])


In [7]:
print(arr1 + arr2)


[3 6 9]


In [8]:

# Broadcasting
print(arr1 + 4)


[5 6 7]


In [9]:
# Reshaping and flattening
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])



In [10]:
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
flattened = reshaped.flatten()


In [12]:
print(flattened)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# Modify flattened array
flattened[0] = 99


In [14]:
print(flattened)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])
print(arr1 + arr2)
print(arr1 + 4)

[3 5 7]
[5 6 7]


In [18]:
arr1 = np.array([1, 2, 3])


In [22]:
arr2 = np.array([[2], [4], [6]])
print(arr1+arr2)


[[3 4 5]
 [5 6 7]
 [7 8 9]]
